### ISSUE TITLE
Covariance implementation has bugs

### ISSUE THREAD

**Issue by surhud** [surhudm/savitzky_golay_with_errors#1]
Covariance implementation is incorrect. It cannot just work using polyfit. We need to call the leastsq procedure explicitly. This will result in a speed decrease.

**Comment by benediktdiemer** [comment]
I just implemented leastsq for covariant errors in the profile fitter in colossus. Let me know if you would like the code

**Comment by surhudm** [comment]
There is an analytical solution to this problem. So I would prefer the
analytical solution as it might be faster. I have a covariant error
implementation of leastsq as well based on our previous email exchanges on
this.
